services:
  - type: web
    name: fortnite-shop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN